### ISSUE TITLE
Unable to drag/drop nifti file into mni viewer

### ISSUE THREAD

**Issue by mchua91** [netstim/leaddbs#1002]
Error when trying to drag/drop nifti file into mni viewer. Can load by going to "Add object" ->  "Open ROI", but was nice to have the option of simply doing drag/drog.

<img width="773" alt="Screenshot 2023-04-27 at 3 04 35 AM" src="https://user-images.githubusercontent.com/84029195/234786817-c4cbc2a8-2ac3-4609-9ddd-42ddfddd03cb.png">

**Comment by ningfei** [comment]
Should be fixed now.
