### ISSUE TITLE
Error upon visualizing atlas in patient space.

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#1011]
Before opening the 3D viewer when attempting to visualize a scene in native space, Lead-DBS issues this error:

Error using findjobj
Error using findjobj
Findjobj only works with Java-based figures, not web-based (App Designer) uifigures

Error in ea_roi/breathelife (line 217)
                jtoggle = findjobj(obj.toggleH);

Error in ea_roi (line 176)
                breathelife(obj);

Error in ea_genatlastable>load_structure (line 357)
        structure=ea_roi(fname,pobj);

Error in ea_genatlastable (line 142)
                    lstructure=load_structure([root,filesep,mifix,options.atlasset,filesep,'lh',filesep,atlases.names{atlas}],atlases,atlas);

Error in ea_ptspecific_atl (line 20)
            ea_genatlastable(atlases,[proot,'atlases',filesep],options);

Error in ea_autocoord (line 219)
            ea_ptspecific_atl(options);

Error in ea_run (line 103)
                    ea_autocoord(options);

Error in lead_dbs/run_button_Callback (line 1248)
            ea_run('run', options);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...

Error in matlab.ui.internal.controller.uicontrol.UicontrolRedirectStrategy/executeCallback (line 231)
                    feval(callback{1}, src, event, callback{2:end});

Error in matlab.ui.internal.controller.uicontrol.PushButtonRedirectStrategy/handleCallbackFired (line 13)
            executeCallback(obj, src, event);

Error in matlab.ui.internal.controller.uicontrol.PushButtonRedirectStrategy>@(varargin)obj.handleCallbackFired(varargin{:}) (line 19)
            component.ButtonPushedFcn = @obj.handleCallbackFired;
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by ningfei** [comment]
can't reproduce but should be more robust with the new commits.
