### ISSUE TITLE
BIDS problem for PseudoM in Network Mapper

### ISSUE THREAD

**Issue by Kinway25** [netstim/leaddbs#1021]
BIDS notation should be ignored when using PseudoM (which works fine in other explorers)
![Selection_1390](https://github.com/netstim/leaddbs/assets/35195806/80381ca6-d5f5-4ee7-b7b2-de3eba554956)

**Comment by ningfei** [comment]
@Kinway25 could you send me the PseudoM you used so I can easily reproduce this?

**Comment by ningfei** [comment]
fixed in 745dd92
