### ISSUE TITLE
VTA estimation crashes

### ISSUE THREAD

**Issue by VoodooCode14** [netstim/leaddbs#1049]
When estimating VTAs on 3D visualized DBS contacts on Linux, the standalone client searches for libgfortran.so.**3**. However, the current version provided through apt is libgfortran.so.**5**. Creating a soft link named after version 3 pointing at version 5 doesn't work either.

See the error message below:
Invalid MEX-file '/usr/local/LeadDBS/application/LeadDBS_mcr/LeadDBS/packages/lead/ext_libs/fieldtrip/ea_calc_stiff_matrix_val.mexa64': libgfortran.so.3: cannot open shared object file: No such file or directory

Error arises from here:
Error in ea_calc_stiff_matrix_val_wrapper (line 6)
Error in ea_genvat_horn>ea_sb_calc_stiff (line 9103)
Error in ea_genvat_horn>ea_ft_headmodel_simbio (line 7903)
Error in ea_genvat_horn (line 209)
Error in ea_stimparams>stimulate_Callback (line 1129)
Error in gui_mainfcn (line 95)
Error in ea_stimparams (line 42)
Error in Matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ea_stimparams('stimulate_Callback',hObject,eventdata,guidata(hObject))
Error using waitforallfiguresclosed (line 16)
Error while evaluating UIControl Callback.

**Comment by ningfei** [comment]
symlink version 5 to version 3 won't solve the compatibility issue. Can use [ext_libs/fieldtrip/libgfortran.so.3](https://github.com/netstim/leaddbs/raw/classic/ext_libs/fieldtrip/libgfortran.so.3). Besides, it's not recommended to use the current standalone version. It's very much outdated. We will probably provide a new one once the new release is ready.
