### ISSUE TITLE
Issue with adding stimulation parameters in lead group

### ISSUE THREAD

**Issue by GaranceMeyer** [netstim/leaddbs#1054]
Hi, I can't add stimulation parameters anymore in lead group. I encounter this with different datasets and Lauren could reproduce the issue. I have no clue about the source of the issue. 
Thanks ! 

```
Subscripted assignment between dissimilar structures.

Error in ea_stimparams>nextpt_Callback (line 3097)
    gS(actpt)=S;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ea_stimparams (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ea_stimparams('nextpt_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
```

**Comment by ningfei** [comment]
can't reproduce. Can export and send over the miniset so I can test it.

**Comment by ningfei** [comment]
@nrajamani3 [(https://github.com/netstim/leaddbs/blame/1742967e4556779de523e0e0a5bac1f2699dc17c/helpers/group/ea_initializeS.m#LL83C3-L83C3)](https://github.com/netstim/leaddbs/blame/1742967e4556779de523e0e0a5bac1f2699dc17c/helpers/group/ea_initializeS.m#LL83C3-L83C3)

Hi Nanditha, I saw you commented out this line, is it for ClearTune? It leads to the above error Garance encountered.

**Comment by ningfei** [comment]
5f79e9a
