### ISSUE TITLE
Issues when importing dicoms in two steps

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#1061]
If I run a first dicom import and do not select postop images, then run it again and import postop images, the following error is shown:

Error using BIDSFetcher/checkModality
Post-op images not properly defined!

Error in BIDSFetcher/getSubj (line 234)
            [preferMRCT, bothMRCTPresent] = checkModality(obj, subjId, preferMRCT);

Error in ea_switchctmr (line 35)
    subj = bids.getSubj(subjId{1}, preferMRCT);

Error in ea_load_pts (line 239)
    ea_switchctmr(handles);

Error in ea_run (line 117)
                ea_load_pts(getappdata(options.leadfigure, 'handles'), getappdata(options.leadfigure, 'uipatdir'));

Error in lead_dbs/run_button_Callback (line 1290)
            ea_run('run', options);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by jAchtzehn** [comment]
Long time no see :) I have regained some time on research, so I will look into this!
