### ISSUE TITLE
[BUG]: Can't get the devel version to run

### ISSUE THREAD

**Issue by vlitvak** [netstim/leaddbs#1081]
Hi,

I'm trying to get the devel version to run on Win 10. Matlab 2023a. Reset the path to default and added just SPM and lead-dbs. I get the following error:

Not enough input arguments.

Error in ea_convertGUIDEArguments (line 37)
        appFigure = ancestor(event.Source, 'figure');

Error in lead_dbs/lead_dbs_OpeningFcn (line 874)
            [hObject, eventdata, handles] = ea_convertGUIDEArguments(app); %#ok<ASGLU>

Error in lead_dbs>@(app)lead_dbs_OpeningFcn(app,varargin{:}) (line 2727)
                runStartupFcn(app, @(app)lead_dbs_OpeningFcn(app, varargin{:}))

Error in appdesigner.internal.service.AppManagementService/runStartupFcn (line 135)
            startupFcn(app);

Error in matlab.apps.AppBase/runStartupFcn (line 68)
            ams.runStartupFcn(app, startfcn);

Error in lead_dbs (line 2727)
                runStartupFcn(app, @(app)lead_dbs_OpeningFcn(app, varargin{:}))

Error in lead>lead_OpeningFcn (line 86)
            lead_dbs;

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in lead (line 42)
    gui_mainfcn(gui_State, varargin{:});

Thanks,

Vladimir

**Comment by ningfei** [comment]
hard to tell based on the above info. We can schedule a quick zoom?

**Comment by vlitvak** [comment]
I'm in the office today so any time before the end of the day is fine.

**Comment by ningfei** [comment]
MATLAB path cache problem. Solved by `restoredefaultpath` and restart MATLAB.
