### ISSUE TITLE
[BUG]: Visualizing VTAs

### ISSUE THREAD

**Issue by lahart21** [netstim/leaddbs#1085]
![Screenshot 2023-08-29 at 7 42 18 AM](https://github.com/netstim/leaddbs/assets/66320336/90557485-0179-46cf-8371-17eac7427972)
![Screenshot 2023-08-29 at 7 42 24 AM](https://github.com/netstim/leaddbs/assets/66320336/1c802003-2c20-49d6-8b85-c00527af4940)

**Comment by ningfei** [comment]
FSL env issue in shell setting.
