### ISSUE TITLE
v3.0 Import Issue 

### ISSUE THREAD

**Issue by PhilipMosley** [netstim/leaddbs#1091]
Hi - trying out v3.0 for the first time - have run into issue with importing from DICOMs / nifti files

It seems to convert ok and pulls out the relevant metadata from the scans but they fail to load in slicer and I can't proceed past this stage.

Mac Pro M1 Max Chip, Matlab 2023a

Thank you for any pointers.

<img width="1635" alt="Screenshot 2023-09-08 at 11 19 36 am" src="https://github.com/netstim/leaddbs/assets/11986354/769c0348-3551-4117-80e1-b5343613636a">

<img width="1079" alt="Screenshot 2023-09-08 at 11 11 29 am" src="https://github.com/netstim/leaddbs/assets/11986354/78372d05-f07b-4942-a501-3484b9abd3e6">

**Comment by andreashorn** [comment]
Hi Phil, what I could imagine is that you have a function on the path that is called histogram.m and obscures the official matlab function with the same name?
Could you run "which histogram" in the command line and see where it points to? If its not a built in function but from a different package, would remove that package from the path.

**Comment by PhilipMosley** [comment]
Aha! You are correct. Problem solved - thank you and will close this. Much appreciated.
