### ISSUE TITLE
Detect correct coregistration here

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#160]
https://github.com/leaddbs/leaddbs/blob/89fd00f7fb6926b9319a39bf2181ed3a110d84d2/ea_runpacer.m#L6

On this line would need to check whether ANTs was called or instead BRAINSFit or FLIRT (new).
e.g. like in ea_genctmask lines 11-21.
@ningfei could you help us on this? Is there a function to read in FLIRT or BRAINSFit matrices to add to the header mat?

Thanks, @adhusch and @andreashorn :)

**Comment by ningfei** [comment]
@andreashorn where can I find the function `ea_genctmask`?

**Comment by andreashorn** [comment]
Sorry, forgot to push it, now it's there :)

**Comment by ningfei** [comment]
so line 6 in ea_runpacer.m would support BRAINSFit and FSL as well as ANTs? This can be done by converting fsl mat file to itk format (the brainsfit output is already itk format as ants output).  I will add additional binary to ext_libs to do this.
