### ISSUE TITLE
Gather first experience with standalone versions

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#17]
For some people, it might be nice to just have a standalone version of Lead so they don't need Matlab at all. Maybe we should start to explore this a bit and if there are no real obstacles we could even think about a deployment routine for standalone repos of lead-dbs.
I know that they managed to make a standalone version of SPM at the FIL, but there were some obstacles in the beginning..

http://www.mathworks.com/products/compiler/?refresh=true

**Comment by ningfei** [comment]
as we already made it :D thanks to Simon
