### ISSUE TITLE
error in ea_showcortex(line148): too many inputs asked

### ISSUE THREAD

**Issue by lemonskiller** [netstim/leaddbs#191]
I want to use [cortical reconstruction visualization] but it says:
too many inputs asked,maybe miss"[]"

error ea_showcortex (line 148)
atlas = files{~cellfun(@(x) isempty(regexp(x, ['annot_',options.prefs.d3.cortex_defaultatlas,'.mat'], 'match')),
files)};

error ea_elvis>opencortexviewer (line 491)
cortex=ea_showcortex(resultfig,options);

**Comment by andreashorn** [comment]
Hi lemonskiller, please use our official support channels for support questions.
https://www.lead-dbs.org/helpsupport/

Best, Andy
