### ISSUE TITLE
Command line command "-recon all type"

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#348]
It would be great to be able to run lead-dbs standalone from the commandline by supplying a folder with preop and postop images (in correct name already) and to then run the whole automated pipeline with i) coreg, ii) normalization, iii) brainshift correction and iv) pacer.

Additionally, it would be great if this also worked when supplying a BIDS folder - thus, as a first step, it would run the new import BIDS step.

**Comment by simonoxen** [comment]
This does the recon all part, using the "-process" command. Will be included once we compile again

[https://github.com/netstim/leaddbs/commit/2f2c037748dc3510ae6c39c2b3ba5378dd060fd4](url)

**Comment by simonoxen** [comment]
Added BIDS opt in a7b13690b3747049cbccb26a9058675601d7e705
