### ISSUE TITLE
Remove unneccessary camera jumps when building the 3D viewer

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#353]
As discussed on slack, when setting the 3D view to "default", it would be great to not change the camera too often and set it to default view already while building the scene.

**Comment by simonoxen** [comment]
This was solved here 6e85757f428e68a68269e221ace8b04123d047a6 . Should we close this one? Or any thoughts

**Comment by ningfei** [comment]
yes, can be closed now I think! I will leave it for you to close it? ;)
