### ISSUE TITLE
override BIDS lookup

### ISSUE THREAD

**Issue by cboulay** [netstim/leaddbs#390]
Using BIDS layout, I have 2 different preop *T1w, one of them has _ce-Gd (contrast enhancement Gadolinium) and the other has _ce-None.

I would like to use the None version without deleting the Gd version or giving it a non-compliant name, but the current lookup doesn't discriminate between them so I end up with 2 t1s in the derivatives folder.

Do you think we could add `options.prefs.lead2bids_override` (or please provide a better name) in which the user can replace cells in the last column of [`lead2bids_lookup`](https://github.com/netstim/leaddbs/blob/48113b6d089ef5603ece1b257f809aa22bcc0bd5/ea_read_bids.m#L63-L78), indexed by the first column? And could we also make the file lookup use regex?

I'm willing to do the work, I just need a little bit of help before I start. Can someone (@simonoxen ?) please comment the [code in the nested for loops](https://github.com/netstim/leaddbs/blob/48113b6d089ef5603ece1b257f809aa22bcc0bd5/ea_read_bids.m#L80-L91) so I can be sure what's going on?

First, it looks like the code is meant to accommodate multiple matches for (e.g.) `preop_folder`, hence the `for b = 1:length(lead2bids_lookup{a,2})`. Is that correct? Is that an acceptable structure?

Second, if multiple files are found for a given lookup, then everything after the first file will get suffixed with `_1`, `_2`, etc. But note that `c` is reset for each `b` (folder), so if files are found in different folders then they will replace the previous outputs. I'm guessing this is not intentional, but I wanted to check.

**Comment by cboulay** [comment]
Also, I noticed in the `lead2bids_lookup` table that there wasn't an entry for preop_folder and CT. Is this intentional? I haven't been following closely enough to know whether or not you've abandoned using preop CTs for either multispectral normalization and post-pre coregistration.

**Comment by neumann-wj** [comment]
Hi Chadwick, 
That is a good idea. 
Sure, I will have a look at it again and comment for some guidance.

Best wishes
Julian

**Comment by neumann-wj** [comment]
Hi @cboulay and @andreashorn  I have now commented the file:
https://github.com/netstim/leaddbs/blob/develop/ea_read_bids.m 

please ask if you have any more questions. 

Best wishes
Julian

**Comment by cboulay** [comment]
OK great thanks. I'll close the issue when I have a PR ready. Probably tomorrow :)

**Comment by cboulay** [comment]
Hi @neumann-wj , the PR isn't ready yet, I just had another question.

Instead of asking users to provide their own regexp in `.ea_prefs.m`, we could instead use [bids-matlab](https://github.com/bids-standard/bids-matlab) and asking them to provide more straightforward filters. In the single-subject case, the benefit is rather small and maybe not worth adding another dependency. However, if there's a long-term goal to also use BIDS for analyzing lead _groups_ (which is really where BIDS shines), then maybe it's worth adding it as a dependency now so we can get the (small) benefit now.

By the way, from your code comments it seems there was a misunderstanding. I don't really need Lead-DBS to be aware of my gd-enhanced images. I only want to be able to tell Lead-DBS to ignore those images, without having to remove them my BIDS folder.

**Comment by jAchtzehn** [comment]
Hello @cboulay! 

just to let you know: we are currently in the process of restructuring lead-dbs to a BIDS-like standard. This will also include a DICOM->.nii->BIDS conversion tool with custom lookup tables for files with different options for DICOM->.nii conversion (dcm2niix, dicm2nii, SPM). 

Cheers!
