### ISSUE TITLE
Connectomes with subsets do not work in Lead group

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#393]
See bug report here:

https://www.lead-dbs.org/forums/topic/ppmi-72-connectivity-metric-problem/#post-9404

**Comment by ningfei** [comment]
See https://github.com/netstim/leaddbs/blob/develop/lead_group.m#L1052 
The fMRI part is not yet supported. Maybe those fMRI connectomes should not appear in the `fiberspopup`?
