### ISSUE TITLE
Automatically add colors to lead group

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#414]
In Lead-Group, if a new group is added (e.g. patient #2 is changed from group 1 to group 2 and group 2 had not been present before), we should define default colors for the groups.
Only if user manually changes them should they be reassigned.

Optimally, could take the LHC-based colors from gramm by default:
https://blogs.mathworks.com/images/pick/Sean/maingramm/grammexamples.html

**Comment by ningfei** [comment]
Added in 3f5053e
