### ISSUE TITLE
Feature Request: Deface images

### ISSUE THREAD

**Issue by greydongilmore** [netstim/leaddbs#436]
Given the majority of users are using clinical scans it would be a great feature to have the images defaced at some-point during the pipeline. This would make sharing output data much easier.

I have attempted to deface nifti files prior to running Lead-DBS but it often fails during co-registration/normalization. If the Lead-DBS pipeline requires non-defaced images as input then having an option to deface the output would be excellent.

**Comment by ningfei** [comment]
Hi Greydon, thanks! Sounds a great idea! I will keep it in mind and put it on to-do :)

**Comment by jAchtzehn** [comment]
@ningfei, if you have not already started working on it, I would do so!

**Comment by ningfei** [comment]
Cool! Feel free to do so :) @jAchtzehn

**Comment by jAchtzehn** [comment]
@greydongilmore, the feature to deface anatomical images has been added to the latest development branch commit (#489). Please feel free to test it out, I am open for any feedback.

**Comment by jAchtzehn** [comment]
I think this feature request can be closed now after the merge.
