### ISSUE TITLE
lead-dbs.org is not responding

### ISSUE THREAD

**Issue by rcwelsh** [netstim/leaddbs#535]
I was following the like to go to lead-dbs.org to find out more information about installing atlases, but the link appears to be dead, or at least is not responding. I've tried from two different computers, and two different web browsers.

**Comment by cboulay** [comment]
Might just be the redirects. Fully qualified https://www.lead-dbs.org seems to be working for me (albeit a bit slow).

**Comment by ningfei** [comment]
yes, it's also slow here in Berlin as I tested... Guess it might be temporary network issue on your side? @rcwelsh

**Comment by rcwelsh** [comment]
Oddly, I can get when I am not within my university’s firewall, but if I’m inside the firewall I can’t access.

Thanks!

Robert


From: Ningfei Li ***@***.***>
Reply-To: netstim/leaddbs ***@***.***>
Date: Monday, April 12, 2021 at 12:14 PM
To: netstim/leaddbs ***@***.***>
Cc: ROBERT CARY WELSH ***@***.***>, Mention ***@***.***>
Subject: Re: [netstim/leaddbs] lead-dbs.org is not responding (#535)


yes, it's also slow here in Berlin as I tested... Guess it might be temporary network issue on your side? @rcwelsh<https://github.com/rcwelsh>
