### ISSUE TITLE
Path format issues (for matlab tools and windows platform)

### ISSUE THREAD

**Issue by oprienrico** [netstim/leaddbs#751]
Hi everyone,
I've ran into some issues with the current develop version regarding paths, specifically on windows platforms.
This is triggered by using ea_path_helper, which wraps the path with "" on windows platform, making the resulting pat incompatible with matlab path-based tools (fileparts, rmdir, ls, dir, delete, ...).

I've suggested possible changes in this pull request:
https://github.com/netstim/leaddbs/pull/746

To ensure the "right" path is supplied to the matlab method as needed, I've added ea_path_formatlab method.

In detail:
The issue is triggered when using a path with a '"\path\to\file\T1w.nii"' structure.
this is caused by using ea_path_helper, which on windows adds the quotes to solve issues with spaces (which it is not done on unix/macOS/ubuntu)
Specifically, this can happens with cfg.moving, cfg.fixed, and cfg.outputimage are wrapped by quotes ("") when passed to ea_ants_run (on windows platform)

When using fileparts, that will trim to '"\path\to\file' with the " termination, which will cause issues in the subsequent code.
All these points cause ea_mkdir to fail, or creation of invalid concatenated paths.

To support this, I've added new method ea_path_formatlab, which is supposed to "invert" what is done by ea_path_helper, for a single path for now.

For ea_path_helper, now it ensures quotes are not added two times if handling windows path, which had already been parsed through ea_path_helper, or was "quoted" to not have issues with spaces on the path.

Added some extra helpers as well
-ea_string_startendwithquotes: checks if string has quotes
-ea_stripquotes: strip quotes from string
-ea_fileparts: strips quotes, then runs fileparts, then re-adds the quotes if they were present
-ea_path_formatlab: make path "safe" for handling in matlab ("invert" what is done by ea_path_helper)
-ea_path_escape: escape string path to c-formatted string (for printf)

**Comment by ningfei** [comment]
thanks! I will check and merge it soon.

**Comment by ningfei** [comment]
Hi @oprienrico, I looked into this issue and did some tests. I think the easiest fix would be using **`` ` ``** to escape space on Windows (similar to `\` on Unix) and use powershell to run the system command:
``system('powershell -InputFormat None -Command fslhd D:\test` folder\t1.nii')``
what do you think?

**Comment by oprienrico** [comment]
Hi @ningfei , that alternative works for escaping paths in windows (commands based in powershell), would work, but only in the case that there is no space used to begin with.

The issue here is mainly that some modules generate the path while calling ea_path_helper at some point, which makes that path invalid for matlab functions (which interpret escape characters as normal characters).

This is also a problem on Unix/MacOs when part of the path gets hashed. 
The reason why it is not really problem on Unix/MacOs, is that to begin with the condition for escaping strings within ea_path_helper is basically never triggered (specifically, regexprep(filepath{i},'[[''() &]]', '\\$0')) , as paths with spaces are not currently supported, and an alert appears mentioning it to the Leaddbs user.

An example on windows, but the same is valid on Unix/MacOs
e.g. if I have a file structure such as (folder with space in the name):
test folder\
test folder\file1.txt
test folder\file2.txt

I can use :
system('powershell -InputFormat None -Command ls test` folder')
which will return 
Mode                LastWriteTime         Length Name                                                                   
----                -------------         ------ ----                                                                   
-a----        5/30/2022   9:02 PM              0 file1.m                                                                
-a----        5/30/2022   9:03 PM              0 file2.m 

however if I input the same string as argument of matlab functions
dir('test` folder')
Output: 'test` folder' not found.

ls('test` folder')
Output: 'test` folder' not found.

This for example is what happens in ea_ants_run, at the lines:
ea_mkdir(fileparts(cfg.outputbase));
ea_mkdir(fileparts(cfg.outputimage));
As the path that is passed to ea_mkdir is already escaped (and again it only happens in windows as no strings are generally escaped in Unix/MacOs, if there are no spaces in the path to begin with)


so there are two ways to "solve" this issue:
1) ensure that the ea_path_helper is invoked only and solely before passing them to "system calls". This however would require to slightly rewrite how now ANTS module, and some other modules that were rewritten due to BIDS.
2) or just in general having a function to sanitize the input to "matlab functions" that use path, unescaping/removing the escape characters. This could be easier, but maybe the first option is cleaner. This is the scope of ea_path_formatlab (which for now only handles the current "" in windows).
3) using a different escape character on windows, but at that point no escape character is really needed if no spaces are allowed). If a path would be escaped, that would still need to be unescaped before using it with a matlab function.

On a tangent note, I am not sure powershell is enabled in all windows machines, as some institutions may disable it for "safety concern". 

what do you think?

**Comment by ningfei** [comment]
I see. Thanks for the investigation. I think those rewritten parts related to ea_path_helper were unintentionally made. It should be only be passed to the system call. Otherwise it will mess up the paths using elsewhere. I would prefer to the _cleaner_ fix if you would also agree. I will check through the code to make sure it's called properly.

**Comment by oprienrico** [comment]
I also agree. So option 1?
Should I backtrack all the "inappropriate" calls to ea_path_helper and rewrite part of the ANTS wrapper module?
I did not see anyone changed it in the meantime, just making sure this is not being addressed in another branch

**Comment by ningfei** [comment]
yes, aggreed, will use option 1 to solve the issue. It's not being addressed in another branch. But will find the time to solve it and let you know. I'm also think about a more general solution to maybe add a function `ea_system()` to replace builtin `system`, in which the system call could be properly handled under different OS.

**Comment by oprienrico** [comment]
Hi @ningfei  are you already tackling this? otherwise I will do it as I do need it as well.
