### ISSUE TITLE
Postop MRI images are not properly named if acq-tag is set

### ISSUE THREAD

**Issue by jAchtzehn** [netstim/leaddbs#755]
Thank you @lahart21 for reporting this! 

When an MRI image is selected as the postop image and it also has an `acq-` tag, the patient cannot be loaded into lead-dbs.

E.g. the post-op MRI image would be called:
`sub-E244_ses-postop_acq-ax_ax_MRI.nii.gz`
which throws an error on importing this patient to lead dbs:
```
Error using BIDSFetcher/checkModality (line 132)
Post-op images not properly defined!

Error in BIDSFetcher/getSubj (line 140)
            [preferMRCT, bothMRCTPresent] = checkModality(obj, subjId, preferMRCT);

Error in ea_switchctmr (line 35)
    subj = bids.getSubj(subjId{1}, preferMRCT);

Error in ea_load_pts (line 282)
    ea_switchctmr(handles);

Error in lead_dbs>DropFcn (line 154)
    ea_load_pts(handles, patdir);

Error in lead_dbs>@(obj,evt)DropFcn(obj,evt,handles) (line 111)
    @(obj,evt) DropFcn(obj,evt,handles), ...

Error in dndcontrol.DndCallback (line 147)
                                feval(obj.DropFileFcn,obj,evt);
```
 
Proposed solution:
prevent `acq-` tag in the filenames for postop MRI images.

What do you think @ningfei?

**Comment by ningfei** [comment]
I think we need to fix the duplicated `ax` label here. `acq` entity will still be needed since we need to differentiate different kinds of postop MRI (it has to be one of ax, cor, sag). We need ax for localization but other images can be used for visualization if they exist.

**Comment by ningfei** [comment]
okay, cool. Need to trace down where the duplicated label was inserted.
