### ISSUE TITLE
When atlas contains fiber tracts the 3D atlas show/hide menu does not work

### ISSUE THREAD

**Issue by oprienrico** [netstim/leaddbs#757]
This is caused by ea_getsubindex, which uses as name for the structure the what obtained with ea_niifileparts, which however does not strip the extension from a file terminating in .mat, and returns it unaltered.

Suggested bugfix at this pull request: https://github.com/netstim/leaddbs/pull/756

**Comment by oprienrico** [comment]
Pull request now merged to mainline

**Comment by ningfei** [comment]
Fixed  by #756, thanks!
