### ISSUE TITLE
BIDS - can't start GUI 

### ISSUE THREAD

**Issue by GaranceMeyer** [netstim/leaddbs#769]
Hi, I tried to install lead dbs bids version with Konstantin and I can't even open the GUI. Here is the error :

```
Error using save
Variable 'recentfolders' not found.

Error in ea_initrecent (line 16)
save([earoot, 'common', filesep, 'ea_recent', type, '.mat'], 'recentfolders');

Error in lead_dbs>lead_dbs_OpeningFcn (line 61)
ea_initrecent(handles, 'patients');

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in lead_dbs (line 43)
    gui_mainfcn(gui_State, varargin{:});

Error in lead>lead_OpeningFcn (line 87)
            lead_dbs;

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in lead (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in lead>startdbs_Callback (line 215)
lead dbs;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in lead (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)lead('startdbs_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

```

**Comment by ningfei** [comment]
Thanks for the report! First, no panic, but reboot won't fix it unfortunately. `ea_restoreprefs(1,1)` should solve it in such a case. How did you switch to bids version of LeadDBS, using `git checkout develop` or?

**Comment by ningfei** [comment]
To switch branch between `classic` and `develop`, one should use `ea_switch2dev` and `ea_switch2classic` in MATLAB. Git command line and Git GUI should be avoided. Otherwise you might have a corrupt prefs. If the error persists, one can reset the default prefs by `ea_restoreprefs(1,1)`.

**Comment by ningfei** [comment]
Fixed in a57684b8

**Comment by GaranceMeyer** [comment]
Hi Ningfei, no panic at all on my side don't worry! konstantin could make a quick fix (I think ea_restoreprefs was not enough, though). But we thought to report the issue as the same thing already happened to Lauren. I think we cloned the repository with the github app and then switched from there. Have a good day,
Garance
________________________________
De : Ningfei Li ***@***.***>
Envoyé : jeudi 21 juillet 2022 05:09
À : netstim/leaddbs ***@***.***>
Cc : Meyer, Garance ***@***.***>; Author ***@***.***>
Objet : Re: [netstim/leaddbs] BIDS - can't start GUI (Issue #769)


        External Email - Use Caution

Thanks for the report! First, no panic, but reboot won't fix it unfortunately. ea_restoreprefs(1,1) should solve it in such a case. How did you switch to bids version of LeadDBS, using git checkout develop or?

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1LsY0D4sNL6NB_dWX1QJIqYIRyw17N7dbxKnG3FHKd6yBc-CHNr4-sv--_hJ-f6uddpc1N0rLvBKel8WCkWCyNVOBEj6LGEpiuIcJwu5JfLdAkrnZF03Fs0pvzIQ-ok9WyJJ3jClmjQNf98XOz9SbqLfkxzF_pgeWQ5gK4INRQxzh13JevYqudtONkQB0SdgtN1nVRulpFb22Cbyk_mhgiQrSnqaAT-OI-AR-ygPNNygqv74y0zXFckblawQ8S67-RFM-rPnxEBY07pBP_4EZEJyjCabHT72LC2qDlMXEj5eEi7YkFj37H8oukRhXPRNm/https%3A%2F%2Fgithub.com%2Fnetstim%2Fleaddbs%2Fissues%2F769%23issuecomment-1191240172>, or unsubscribe<https://secure-web.cisco.com/1NL5b438BnUKhxpfI1uOyjlxbPcotYGPDCv9uECucJ8x0xjliHOFvCq3a5BupdtPl3_Kx0KvUyC7SFcMn0fIIHa73gF18glqGyvojcqyfOotncc_ZKOxiPPiyb3PJsE2zjEsvIPo1TN8c5HK20sRAQZSbWmLJL7J2s_SelWMQFxgRE0G4ajgm_qGCsjy2PPshG6Yn5-UErN_L8f0jzWxgvLxyB3NBkblpbNC8zhRMbONznrD1aHzWd3jbGOzAsvHp4mCNxY2vLiU43SCfEOaXhln-P0ium_RInpi1VwngLSdFldWmLW1VHbQgf-5lYoAd/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZ3FHV7DNF7MOOKJGW77MILVVEHWPANCNFSM54FKZ4YQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>
The information in this e-mail is intended only for the person to whom it is addressed.  If you believe this e-mail was sent to you in error and the e-mail contains patient information, please contact the Mass General Brigham Compliance HelpLine at https://www.massgeneralbrigham.org/complianceline <https://www.massgeneralbrigham.org/complianceline> .
Please note that this e-mail is not secure (encrypted).  If you do not wish to continue communication over unencrypted e-mail, please notify the sender of this message immediately.  Continuing to send or respond to e-mail after receiving this message means you understand and accept this risk and wish to continue to communicate over unencrypted e-mail.

**Comment by ningfei** [comment]
You can clone the repository, switch to classic branch using github app. And then run `ea_switch2dev` from there.
