### ISSUE TITLE
How to download the normative connectome of 1000 healthy subjects GSP?

### ISSUE THREAD

**Issue by jmmneuro** [netstim/leaddbs#776]
I cannot download the GSP 1000 normative connectome when I use the Lead Connectome Mapper. However, when I watched the general walkthrough video, I known that there must be somewhere that can allow me to download it.
![微信图片_20220801150601](https://user-images.githubusercontent.com/107784923/182091910-b96e7042-f33a-4453-b7a4-2b98d17daec0.jpg)

**Comment by andreashorn** [comment]
Hi jmm, the GSP data is not ours to redistribute but there is an open version in nifti format: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ILXIKS%27
and of course the original data here https://dataverse.harvard.edu/dataverse/GSP. None of them would work directly with lead mapper but should be easy enough to convert or run in other software.
Best, A

**Comment by jmmneuro** [comment]
Many thanks for your reply !
