### ISSUE TITLE
Need to exclude hidden files when using regexpress

### ISSUE THREAD

**Issue by Kinway25** [netstim/leaddbs#780]
Processing on mac results in a bunch of hidden files that are later detected by regexpression routines in Lead-DBS (e.g. reconstrunction files).
These files have to be excluded.

**Comment by ningfei** [comment]
could you show screenshot or details of the problem? e.g., which kind of hidden files

**Comment by Kinway25** [comment]
![Selection_215](https://user-images.githubusercontent.com/35195806/183120256-bc2af952-06b0-408b-ae6d-77eedcd341c2.png)

**Comment by ningfei** [comment]
which function it is? can you show the full stack?

**Comment by ningfei** [comment]
It should have been fixed by recent commits. In the future can use `^(?!\.)PATTERN` to capture only files not starting with `.`
