### ISSUE TITLE
BIDS Electrode Reconstruction Error

### ISSUE THREAD

**Issue by lahart21** [netstim/leaddbs#782]
Lead-dbs looks for electrode reconstruction in the classic format when adding new trajectory 

<img width="1217" alt="Screen Shot 2022-08-05 at 4 07 56 PM" src="https://user-images.githubusercontent.com/66320336/183154679-cc384d02-8e04-499c-9855-3eafa71a9613.png">

**Comment by ningfei** [comment]
Fixed
