### ISSUE TITLE
BUG cancel open dlg in lead import leads to error

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#790]
Selecting output folder and pressing cancel on opendlg results in an error

<img width="1197" alt="Screen Shot 2022-08-10 at 8 03 44 PM" src="https://user-images.githubusercontent.com/1291036/184043311-d30c8908-9cf8-4cfa-98aa-99168a49f0e9.png">

**Comment by nrajamani3** [comment]
Closing with new commit.
