### ISSUE TITLE
ea_menu_addspace.m issue

### ISSUE THREAD

**Issue by akapp** [netstim/leaddbs#807]
Under `/classic` branch `ea_menu_addspace.m `Line 7 fails to deal with a cell of strings, cellfun added to line 7 to deal with this case.

Original line 7: `[~, spaces] = fileparts({spaces.folder}');`

New suggested line 7: `[~, spaces] = cellfun(@fileparts,{spaces.folder}','UniformOutput',false);`

Under the `/develop` branch `ea_regexpdir` Line 31 fails to deal with a cell of strings, cellfun added here also deals with this issue.

Original line 31: list = `fileparts(list(isfolder(list)));`

New suggested line 31: `list = cellfun(@fileparts,list(isfolder(list)),'UniformOutput',false);`

**Comment by ningfei** [comment]
thanks for the fixes! ecf7438

**Comment by ningfei** [comment]
@akapp btw, which matlab version are you using? `fileparts` supports cell string input as we tested, at least it works from R2020b.
