### ISSUE TITLE
BUG: Importing preop images only

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#826]
…seems still not to work. – @jAchtzehn could you please have a look? Thx!
<img width="1715" alt="Screen Shot 2022-09-15 at 3 47 04 PM" src="https://user-images.githubusercontent.com/1291036/190495736-f46f1193-ed23-45f3-aca2-f2db32b07e24.png">

**Comment by andreashorn** [comment]
(Used the DICOM tool to import a subject with preop data only).

**Comment by ningfei** [comment]
@andreashorn couldn't reproduce. Simon and I tested today with preop only patient DICOM import. There was some issue but should have been fixed. Happy to have a test with your data

**Comment by andreashorn** [comment]
Sending data on slack

**Comment by andreashorn** [comment]
Also got this error when running refresh normalization check figure in a preop only setting.

<img width="900" alt="Screen Shot 2022-09-15 at 8 40 59 PM" src="https://user-images.githubusercontent.com/1291036/190532469-90da0d9e-d0a9-4885-a337-c08664b77bc9.png">
<img width="760" alt="Screen Shot 2022-09-15 at 8 40 55 PM" src="https://user-images.githubusercontent.com/1291036/190532470-0fe946a6-1674-4335-82d6-65818cdccd94.png">

**Comment by andreashorn** [comment]
…and this one when running coregistration in BIDS. 

<img width="864" alt="Screen Shot 2022-09-15 at 8 47 34 PM" src="https://user-images.githubusercontent.com/1291036/190533062-60c9a31f-b845-4f88-b3d2-88ac510b1912.png">
<img width="878" alt="Screen Shot 2022-09-15 at 8 47 29 PM" src="https://user-images.githubusercontent.com/1291036/190533064-a3ee1357-b27d-4050-a26c-6e17fcdc8d47.png">

**Comment by ningfei** [comment]
couldn't reproduce. Should have been fixed.
