### ISSUE TITLE
Error Importing patient from Classic to BIDS

### ISSUE THREAD

**Issue by maemortondutton** [netstim/leaddbs#834]
I am running into an error ("Index exceeds the number of array elements...") when importing the data of a patient in LeadDBS classic to the BIDS format. I have attached the error below. 

<img width="830" alt="Screen Shot 2022-09-29 at 1 38 32 PM" src="https://user-images.githubusercontent.com/66095675/193103408-5df4539f-2a74-4396-8a03-e7bd32e241e2.png">

**Comment by ningfei** [comment]
@maemortondutton could you please set a breakpoint at line 52 of `ea_fslhd` as suggested in the error log and see what's the content of `cmdout`? Usually it's due to that the file was corrupted or so...

**Comment by maemortondutton** [comment]
There was a problem on my end , but it is all fixed now, thank you!
