### ISSUE TITLE
Stimulation in Lead Group doesn't work 

### ISSUE THREAD

**Issue by lahart21** [netstim/leaddbs#837]
Hi all, I was going through lead group files and in the mat file in M.S I can see there are stimulation parameters and the paths do match in M.Patient.List, however when I load the file in lead group and press a pt and click on stimulation parameters I get this error instead of it pulling up the stim parameters. 
<img width="800" alt="Screen Shot 2022-10-01 at 1 28 42 PM" src="https://user-images.githubusercontent.com/66320336/193421268-63eeea19-3ca9-4d60-aaa2-ebae6da75328.png">

**Comment by ningfei** [comment]
Introduced in a55e3ea. Fixed in 4aa55ad
