### ISSUE TITLE
BIDS: error with creating VTAs

### ISSUE THREAD

**Issue by FredSchaper** [netstim/leaddbs#842]
Hello, 
I was trying to compute bilateral VTAs for a subject and it doesn't seem to visualize the left VTA. See attached screenshot and error: 
![Screen Shot 2022-10-07 at 4 48 44 PM](https://user-images.githubusercontent.com/34103264/194650165-8154fe85-d3df-47c5-920c-634634e739ee.png)
![Screen Shot 2022-10-07 at 4 49 17 PM](https://user-images.githubusercontent.com/34103264/194650242-8fbe6eb1-a9e6-48a8-803c-48dd7c0aee8f.png)
This happened in two independent patients with different DBS targets. I tried multiple atlases, electrode models, or methods to create VTA (e.g. simbio or fast field) but unfortunately the same keeps happening: it won't visualize the left VTA in the viewer. FYI: it does compute the left VTA, see this screenshot of the stimulations folder: 
![Screen Shot 2022-10-07 at 4 51 45 PM](https://user-images.githubusercontent.com/34103264/194650570-cb27886c-e365-4abe-bd2f-6a64cf182c7c.png)
Thanks so much for your help! 
Best, 
Fred

**Comment by Kinway25** [comment]
The VTA is created though, just a problem with the automated import to the electrode scene

**Comment by ningfei** [comment]
@FredSchaper could you please set a breakpoint there at line 62 of `ea_efield_overlap` as indicated by the error information and check what are the dimmensions of `vtanii.img` and `atlasnii.img`? Thanks!

**Comment by FredSchaper** [comment]
@ningfei thanks! see attached screenshots of dimensions. 

![Screen Shot 2022-10-11 at 10 26 05 AM](https://user-images.githubusercontent.com/34103264/195119533-43b0cff5-6c59-4278-996c-269fecb7c079.png)
![Screen Shot 2022-10-11 at 10 25 30 AM](https://user-images.githubusercontent.com/34103264/195119537-e2d552f5-ca2c-4c42-9b08-94e6cd0dd7bd.png)

**Comment by ningfei** [comment]
seems the atlas file was not correctly resliced. Which atlas did you use? Could you please check in the atlas folder to see if there're duplicated file of the same structure (nii and nii.gz both exist, as suggested in the warning)?

**Comment by FredSchaper** [comment]
I used both the DISTAL nano, or minimal, or the THOMAS atlas. I checked the atlas folders and there are no duplicated files in those atlas folders.

**Comment by ningfei** [comment]
since I can't reproduce this. guess it might be a macos specific problem that you don't have proper permission to run flirt.mci64 shipped with leaddbs

**Comment by FredSchaper** [comment]
okay, looks like I do have permission to run flirt.maci64. 
![Screen Shot 2022-10-18 at 2 27 52 PM](https://user-images.githubusercontent.com/34103264/196545207-cabca661-915c-4c74-a715-49d2d88593f2.png)
Also re-installed lead dbs and the templates again, but the same issue arises with multiple different patients.  
![Screen Shot 2022-10-18 at 5 09 40 PM](https://user-images.githubusercontent.com/34103264/196545435-00ffec0d-8f67-4ced-832a-6bfbd00fb9d2.png)
Anything else I could try? 
Thanks!

**Comment by ningfei** [comment]
Hi @FredSchaper maybe you can set a breakpoint in `ea_efield_overlap` at the line `ea_fsl_reslice(atlasnii.fname, vta, atlasnii.fname, 'trilinear', 0);` to see if the images are correctly resliced? Or we can schedule a zoom to debug it together?

**Comment by maemortondutton** [comment]
Hi @ningfei I am running into this same error when calculating my VTAs.
