### ISSUE TITLE
DICOM import broken?

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#859]
On my end, trying to drag 2 DICOM folders (for 2 patients) onto lead-dbs and running the new "silent mode" import – getting this error below.

<img width="1790" alt="Screen Shot 2022-10-26 at 12 16 43 PM" src="https://user-images.githubusercontent.com/1291036/198079877-1a3355fc-9e9b-40af-a13a-3f276104acd2.png">

**Comment by ningfei** [comment]
@andreashorn wrong screenshot?

**Comment by andreashorn** [comment]
Sorry attached. @lhart mentioned it could be due to her PR.
<img width="559" alt="Screen Shot 2022-10-26 at 12 16 26 PM" src="https://user-images.githubusercontent.com/1291036/198116845-c07b3a93-d057-4388-81d8-a7e660b67446.png">

**Comment by ningfei** [comment]
might work now.

**Comment by andreashorn** [comment]
Doesn't work but also see my slack -> maybe better focus on the new GUI and work from there?
<img width="537" alt="Screen Shot 2022-10-26 at 7 02 56 PM" src="https://user-images.githubusercontent.com/1291036/198154886-7b1178ac-6eb2-44d5-a954-7462b66388ee.png">

**Comment by lahart21** [comment]
<img width="971" alt="Screen Shot 2022-10-28 at 10 32 22 AM" src="https://user-images.githubusercontent.com/66320336/198648777-2c3d9efe-6a3d-426a-9313-5ccfd9d74245.png">

**Comment by ningfei** [comment]
@lahart21 can pull and try again?

**Comment by lahart21** [comment]
Just did, unfortunately same error

**Comment by ningfei** [comment]
@lahart21  same error? maybe you need to restart matlab

**Comment by lahart21** [comment]
@ningfei Yes, I restarted Matlab and set the paths again and its still the same

**Comment by ningfei** [comment]
@lahart21 can't be the same...that error line in your screenshot doesn't exist anymore

**Comment by ningfei** [comment]
can you show me the folder structure you dragged in?

**Comment by lahart21** [comment]
Okay because I ran that same pt previously and nothing happened it made a folder called DICOM inside. Let me get rid of that and try again

**Comment by ningfei** [comment]
solved  as you told me on slack? @lahart21

**Comment by lahart21** [comment]
Yes, thank you!
