### ISSUE TITLE
Can't join Slack (autoinvite) not working

### ISSUE THREAD

**Issue by lrfbranco** [netstim/leaddbs#866]
Hi there!

Sorry, I can't seem to join the slack channel. The autoinvite just gives me the "There's nothing here, yet." ... 
Can someone please invite me? Also, what would be appropriate method to sending my email? On this thread?

Thankss,
Luciano

![image](https://user-images.githubusercontent.com/18337929/199824376-a3453785-0eda-4415-983b-9fc56fc72b46.png)

**Comment by ningfei** [comment]
Hi @lrfbranco just tested, it works from my side. Can also invite you if you send me your email address.

**Comment by lrfbranco** [comment]
Oh nevermind, it's working today!! Thanks
