### ISSUE TITLE
can't find lead mat file 

### ISSUE THREAD

**Issue by emanuellas** [netstim/leaddbs#868]
<img width="888" alt="git_clone_leaddbs_error" src="https://user-images.githubusercontent.com/98845926/200014006-b357ae50-9d83-41e9-8484-667a519a75dc.png">

**Comment by ningfei** [comment]
Hi @emanuellas are you using develop branch intentionally, or? Otherwise, I would recommend you to use classic branch for now. If you see the error above, can try `ea_restoreprefs(1,1)`, usually it helps.
