### ISSUE TITLE
Can't get lead dbs to assign images to post/preop correctly

### ISSUE THREAD

**Issue by GaranceMeyer** [netstim/leaddbs#872]
Hi, 
I'm trying to import a new dataset in leadDBS, bids version. I'm using the niftii files I got from our collaborators. When trying to import using lead dbs or lead import, I am never prompted to select which image is what, and lead dbs assigns some images incorrectly (e.g. postop CT assigned to preop T1). I don't know how to solve this, and Lauren told me that similar issues happened before. Thanks in advance for considering!

**Comment by andreashorn** [comment]
…probably need to call the nifti files as in the classic version (anat_t1.nii or postop_ct.nii, postop_tra.nii etc).
But this is a good point, we don't have a good pathway yet to start off nifti files (if we dont have the dicoms).
