### ISSUE TITLE
BIDS - unable to co-register multiple subjects at once 

### ISSUE THREAD

**Issue by maemortondutton** [netstim/leaddbs#880]
When I try to co-register many subjects in the same patient directory at the same time, it only recognizes the T1 image and not my post-op image. To clarify, it does not throw an error, but rather just does not upload all the images. However, when I run reach patient separately, BIDS recognizes both my T1 and post-op image. I can send you some test patients directly.

**Comment by ningfei** [comment]
Thanks! Garance also reported the same issue. I will try it on my side and let you know if I need your data to test.
