### ISSUE TITLE
BIDS - unable to check-results from multiple patients in the same patient folder

### ISSUE THREAD

**Issue by maemortondutton** [netstim/leaddbs#881]
I am unable to check-results of multiple patients at the same time after I have successfully co-registered and normalized all of the selected patients. I receive this warning (seen below) when I try and check-results for multiple patients: 
<img width="1512" alt="Lead-DBS" src="https://user-images.githubusercontent.com/66095675/201366288-b510a9e0-8ac8-4ea4-b290-a882649647e6.png">

When I check-results for each patient separately, it takes a while to export the co-registered images and then checks-results. I am unsure if this is relevant to the problem above. 

<img width="1184" alt="Screen Shot 2022-11-08 at 4 28 12 PM" src="https://user-images.githubusercontent.com/66095675/201366682-aa3f4bcd-1a7c-472d-a085-828ae5ebaa09.png">

**Comment by ningfei** [comment]
Thanks for the report. Should work now.
