### ISSUE TITLE
Citation problem (?) with some atlases

### ISSUE THREAD

**Issue by Kinway25** [netstim/leaddbs#890]
Hi, when launching the electrode scene with Distal or CIT, I get the following errors. Perhaps they are related? Garance also encountered them
![Selection_583](https://user-images.githubusercontent.com/35195806/202924031-02b7b501-b100-4982-a94c-fa360f984858.png)
![Selection_582](https://user-images.githubusercontent.com/35195806/202924035-1ad054bf-5455-4abc-b996-1fe293943991.png)

**Comment by ningfei** [comment]
fixed. Some citation strings were not stored properly.
