### ISSUE TITLE
WarpDrive crashing upon loading

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#896]
WarpDrive crashing upon loading

<img width="1112" alt="Screen Shot 2022-11-26 at 12 08 50 PM" src="https://user-images.githubusercontent.com/1291036/204100602-a08a63a6-23e0-4fcd-8905-922a2375231c.png">

[error_message.txt](https://github.com/netstim/leaddbs/files/10096690/error_message.txt)

**Comment by simonoxen** [comment]
should be fixed now. please re-open if still crashing
