### ISSUE TITLE
Lead-DBS GUI will revert back to old settings after running

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#964]
When I load an existing patient it will load the last settings (e.g. "Render 3D" and "Check Results" is active and the atlas is set to Brainstem Connectome). If I change these settings (e.g. switch only "Warp Drive" on) and press run, it executes correctly. However, after this, it revers settings back to "Render 3D" and "Check Results".

**Comment by ningfei** [comment]
Should be fixed by 2ac53fd
