### ISSUE TITLE
Manual pre-reconstruct

### ISSUE THREAD

**Issue by Kinway25** [netstim/leaddbs#971]
![Selection_1279](https://user-images.githubusercontent.com/35195806/226974124-d1c43a48-8b18-4a6d-87ea-f9fdc60e3b5f.png)
![Selection_1280](https://user-images.githubusercontent.com/35195806/226974136-97d1b9c2-ca7e-45d6-876e-592cbaeca253.png)

**Comment by Kinway25** [comment]
Yes, Lauren mentioned that it was not reproducible on your side, that is why I tried.
Just imported a legacy patient and tried to re-run the reconstruction.

**Comment by Kinway25** [comment]
Also Melissa reports it

**Comment by nrajamani3** [comment]
Could you tell us the matlab version used?

**Comment by Kinway25** [comment]
R2022a
