### ISSUE TITLE
map from anchor space to template bug

### ISSUE THREAD

**Issue by mchua91** [netstim/leaddbs#978]
Error when trying to use the tool "map from anchor space to template"
<img width="963" alt="Screenshot 2023-03-28 at 1 26 12 AM" src="https://user-images.githubusercontent.com/84029195/228403195-eb3cba55-cf39-459f-b541-bf1638e65f1b.png">

**Comment by ningfei** [comment]
fixed by 1a85cb0 and 1f79f35
