### ISSUE TITLE
Error when running leadDBS v3 on ubuntu and mac 

### ISSUE THREAD

**Issue by ArtMedIntel** [netstim/leaddbs#982]
Hi
I have downloaded the develop branch of lead dbs and I keep getting this error when I try to open it. 
I followed the installation instructions with matlab version and additional toolboxes and SPM12.
when using the master branch v2.7 it is working with literately no errors. 
I had the same problem on macbook and on ubuntu. 
Thank you for your help.

Error using lead>lead_OpeningFcn (line 87)
Error defining property 'Hyperlink' of class 'lead_dbs'. Class named
'matlab.ui.control.Hyperlink' is undefined or does not support property validation.

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in lead (line 42)
    gui_mainfcn(gui_State, varargin{:});

**Comment by ningfei** [comment]
Hi, we are still testing the development v3 version. So better use the classic branch for now. For the specific error you saw, it's due to your matlab version. It should work with R2021a or later versions.
