### ISSUE TITLE
BUG Automatically re-selects buttons after unclicking them

### ISSUE THREAD

**Issue by lahart21** [netstim/leaddbs#983]
Every time I select a pt Render 3D is automatically pressed.

![Screenshot 2023-04-05 at 4 02 56 PM](https://user-images.githubusercontent.com/66320336/230195799-ab0b5121-f247-4b7a-84cb-a64cc70e6026.png)

**Comment by nrajamani3** [comment]
Issue occurs because it is not imported properly - can try deleting that patient from the stack? In any case, working on this: new PR might help resolve this issue.

**Comment by nrajamani3** [comment]
fixed
