### ISSUE TITLE
Should warn to redo BS when redoing CT coreg

### ISSUE THREAD

**Issue by andreashorn** [netstim/leaddbs#988]
If postop to preop coreg as well as brain shift coreg has been performed.
If used recalculates coreg (post to pre) again (e.g. using FSL since ANTs failed), need to delete the brain shift folder and prompt the user that this step needs to be recalculated.

This is a nice to have but would be great to add in to avoid actual mistakes & make the software safer for naive users.

**Comment by ningfei** [comment]
c21001bd
